// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpc/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRoleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleItem) Reset() {
	*x = UserRoleItem{}
	mi := &file_grpc_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleItem) ProtoMessage() {}

func (x *UserRoleItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleItem.ProtoReflect.Descriptor instead.
func (*UserRoleItem) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRoleItem) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserRoleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeptItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  int32                  `protobuf:"varint,1,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptItem) Reset() {
	*x = DeptItem{}
	mi := &file_grpc_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptItem) ProtoMessage() {}

func (x *DeptItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptItem.ProtoReflect.Descriptor instead.
func (*DeptItem) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *DeptItem) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_grpc_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	NotPage       bool                   `protobuf:"varint,3,opt,name=notPage,proto3" json:"notPage,omitempty"`
	Search        *structpb.Struct       `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Sort          *structpb.Struct       `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_grpc_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserListRequest) GetNotPage() bool {
	if x != nil {
		return x.NotPage
	}
	return false
}

func (x *UserListRequest) GetSearch() *structpb.Struct {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *UserListRequest) GetSort() *structpb.Struct {
	if x != nil {
		return x.Sort
	}
	return nil
}

type UserCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Age           int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	UserRoles     []*UserRoleItem        `protobuf:"bytes,7,rep,name=userRoles,proto3" json:"userRoles,omitempty"`
	MainDept      *DeptItem              `protobuf:"bytes,8,opt,name=mainDept,proto3" json:"mainDept,omitempty"`
	UserDepts     []*DeptItem            `protobuf:"bytes,9,rep,name=userDepts,proto3" json:"userDepts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_grpc_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserCreateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreateRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserCreateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserCreateRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserCreateRequest) GetUserRoles() []*UserRoleItem {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *UserCreateRequest) GetMainDept() *DeptItem {
	if x != nil {
		return x.MainDept
	}
	return nil
}

func (x *UserCreateRequest) GetUserDepts() []*DeptItem {
	if x != nil {
		return x.UserDepts
	}
	return nil
}

type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_grpc_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserUpdateRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserBatchDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBatchDeleteRequest) Reset() {
	*x = UserBatchDeleteRequest{}
	mi := &file_grpc_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBatchDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBatchDeleteRequest) ProtoMessage() {}

func (x *UserBatchDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBatchDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserBatchDeleteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserBatchDeleteRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	RoleId        int32                  `protobuf:"varint,3,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_grpc_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserRole) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserRole) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRole) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRole) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserRole) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserDepartment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	DepartmentId  int32                  `protobuf:"varint,3,opt,name=departmentId,proto3" json:"departmentId,omitempty"`
	IsMain        int32                  `protobuf:"varint,4,opt,name=isMain,proto3" json:"isMain,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDepartment) Reset() {
	*x = UserDepartment{}
	mi := &file_grpc_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDepartment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDepartment) ProtoMessage() {}

func (x *UserDepartment) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDepartment.ProtoReflect.Descriptor instead.
func (*UserDepartment) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserDepartment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDepartment) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDepartment) GetDepartmentId() int32 {
	if x != nil {
		return x.DepartmentId
	}
	return 0
}

func (x *UserDepartment) GetIsMain() int32 {
	if x != nil {
		return x.IsMain
	}
	return 0
}

func (x *UserDepartment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserDepartment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender        int32                  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	Status        int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	UserRoles     []*UserRole            `protobuf:"bytes,12,rep,name=userRoles,proto3" json:"userRoles,omitempty"`
	MainDept      *UserDepartment        `protobuf:"bytes,13,opt,name=mainDept,proto3" json:"mainDept,omitempty"`
	UserDepts     []*UserDepartment      `protobuf:"bytes,14,rep,name=userDepts,proto3" json:"userDepts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_grpc_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetUserRoles() []*UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *User) GetMainDept() *UserDepartment {
	if x != nil {
		return x.MainDept
	}
	return nil
}

func (x *User) GetUserDepts() []*UserDepartment {
	if x != nil {
		return x.UserDepts
	}
	return nil
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	List          []*User                `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_grpc_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserListResponse) GetList() []*User {
	if x != nil {
		return x.List
	}
	return nil
}

var File_grpc_proto_user_proto protoreflect.FileDescriptor

const file_grpc_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x15grpc/proto/user.proto\x12\x04grpc\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15grpc/proto/base.proto\":\n" +
	"\fUserRoleItem\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x05R\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\".\n" +
	"\bDeptItem\x12\"\n" +
	"\fdepartmentId\x18\x01 \x01(\x05R\fdepartmentId\"\x1d\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xb9\x01\n" +
	"\x0fUserListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\anotPage\x18\x03 \x01(\bR\anotPage\x12/\n" +
	"\x06search\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06search\x12+\n" +
	"\x04sort\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04sort\"\xb9\x02\n" +
	"\x11UserCreateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x120\n" +
	"\tuserRoles\x18\a \x03(\v2\x12.grpc.UserRoleItemR\tuserRoles\x12*\n" +
	"\bmainDept\x18\b \x01(\v2\x0e.grpc.DeptItemR\bmainDept\x12,\n" +
	"\tuserDepts\x18\t \x03(\v2\x0e.grpc.DeptItemR\tuserDepts\"P\n" +
	"\x11UserUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"*\n" +
	"\x16UserBatchDeleteRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"\x9a\x01\n" +
	"\bUserRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06roleId\x18\x03 \x01(\x05R\x06roleId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\x0eUserDepartment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\"\n" +
	"\fdepartmentId\x18\x03 \x01(\x05R\fdepartmentId\x12\x16\n" +
	"\x06isMain\x18\x04 \x01(\x05R\x06isMain\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"\xaa\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bfullName\x18\x04 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\b \x01(\x05R\x03age\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\tR\tupdatedAt\x12,\n" +
	"\tuserRoles\x18\f \x03(\v2\x0e.grpc.UserRoleR\tuserRoles\x120\n" +
	"\bmainDept\x18\r \x01(\v2\x14.grpc.UserDepartmentR\bmainDept\x122\n" +
	"\tuserDepts\x18\x0e \x03(\v2\x14.grpc.UserDepartmentR\tuserDepts\"x\n" +
	"\x10UserListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\x04list\x18\x04 \x03(\v2\n" +
	".grpc.UserR\x04list2\xbf\x02\n" +
	"\vUserService\x12'\n" +
	"\x06Detail\x12\x11.grpc.UserRequest\x1a\n" +
	".grpc.User\x125\n" +
	"\x04List\x12\x15.grpc.UserListRequest\x1a\x16.grpc.UserListResponse\x12-\n" +
	"\x06Create\x12\x17.grpc.UserCreateRequest\x1a\n" +
	".grpc.User\x12-\n" +
	"\x06Update\x12\x17.grpc.UserUpdateRequest\x1a\n" +
	".grpc.User\x120\n" +
	"\x06Delete\x12\x11.grpc.UserRequest\x1a\x13.grpc.EmptyResponse\x12@\n" +
	"\vBatchDelete\x12\x1c.grpc.UserBatchDeleteRequest\x1a\x13.grpc.EmptyResponseB\x16Z\x14gin/grpc/proto;protob\x06proto3"

var (
	file_grpc_proto_user_proto_rawDescOnce sync.Once
	file_grpc_proto_user_proto_rawDescData []byte
)

func file_grpc_proto_user_proto_rawDescGZIP() []byte {
	file_grpc_proto_user_proto_rawDescOnce.Do(func() {
		file_grpc_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_user_proto_rawDesc), len(file_grpc_proto_user_proto_rawDesc)))
	})
	return file_grpc_proto_user_proto_rawDescData
}

var file_grpc_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_grpc_proto_user_proto_goTypes = []any{
	(*UserRoleItem)(nil),           // 0: grpc.UserRoleItem
	(*DeptItem)(nil),               // 1: grpc.DeptItem
	(*UserRequest)(nil),            // 2: grpc.UserRequest
	(*UserListRequest)(nil),        // 3: grpc.UserListRequest
	(*UserCreateRequest)(nil),      // 4: grpc.UserCreateRequest
	(*UserUpdateRequest)(nil),      // 5: grpc.UserUpdateRequest
	(*UserBatchDeleteRequest)(nil), // 6: grpc.UserBatchDeleteRequest
	(*UserRole)(nil),               // 7: grpc.UserRole
	(*UserDepartment)(nil),         // 8: grpc.UserDepartment
	(*User)(nil),                   // 9: grpc.User
	(*UserListResponse)(nil),       // 10: grpc.UserListResponse
	(*structpb.Struct)(nil),        // 11: google.protobuf.Struct
	(*EmptyResponse)(nil),          // 12: grpc.EmptyResponse
}
var file_grpc_proto_user_proto_depIdxs = []int32{
	11, // 0: grpc.UserListRequest.search:type_name -> google.protobuf.Struct
	11, // 1: grpc.UserListRequest.sort:type_name -> google.protobuf.Struct
	0,  // 2: grpc.UserCreateRequest.userRoles:type_name -> grpc.UserRoleItem
	1,  // 3: grpc.UserCreateRequest.mainDept:type_name -> grpc.DeptItem
	1,  // 4: grpc.UserCreateRequest.userDepts:type_name -> grpc.DeptItem
	11, // 5: grpc.UserUpdateRequest.data:type_name -> google.protobuf.Struct
	7,  // 6: grpc.User.userRoles:type_name -> grpc.UserRole
	8,  // 7: grpc.User.mainDept:type_name -> grpc.UserDepartment
	8,  // 8: grpc.User.userDepts:type_name -> grpc.UserDepartment
	9,  // 9: grpc.UserListResponse.list:type_name -> grpc.User
	2,  // 10: grpc.UserService.Detail:input_type -> grpc.UserRequest
	3,  // 11: grpc.UserService.List:input_type -> grpc.UserListRequest
	4,  // 12: grpc.UserService.Create:input_type -> grpc.UserCreateRequest
	5,  // 13: grpc.UserService.Update:input_type -> grpc.UserUpdateRequest
	2,  // 14: grpc.UserService.Delete:input_type -> grpc.UserRequest
	6,  // 15: grpc.UserService.BatchDelete:input_type -> grpc.UserBatchDeleteRequest
	9,  // 16: grpc.UserService.Detail:output_type -> grpc.User
	10, // 17: grpc.UserService.List:output_type -> grpc.UserListResponse
	9,  // 18: grpc.UserService.Create:output_type -> grpc.User
	9,  // 19: grpc.UserService.Update:output_type -> grpc.User
	12, // 20: grpc.UserService.Delete:output_type -> grpc.EmptyResponse
	12, // 21: grpc.UserService.BatchDelete:output_type -> grpc.EmptyResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_grpc_proto_user_proto_init() }
func file_grpc_proto_user_proto_init() {
	if File_grpc_proto_user_proto != nil {
		return
	}
	file_grpc_proto_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_user_proto_rawDesc), len(file_grpc_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_user_proto_goTypes,
		DependencyIndexes: file_grpc_proto_user_proto_depIdxs,
		MessageInfos:      file_grpc_proto_user_proto_msgTypes,
	}.Build()
	File_grpc_proto_user_proto = out.File
	file_grpc_proto_user_proto_goTypes = nil
	file_grpc_proto_user_proto_depIdxs = nil
}
